services:
  personal-assistant-agent:
    build: .
    env_file:
      - ./.env
    develop:
      watch:
        - path: ./app/
          action: rebuild
        - path: ./docker-compose.yml
          action: rebuild
        - path: ./docker-compose.dev.yml
          action: rebuild
        - path: ./Dockerfile
          action: rebuild
